// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: exchanges.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExchangesServiceClient is the client API for ExchangesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangesServiceClient interface {
	Upvote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	// rpc CreateExchange(CreateReq) returns (CreateRes) {}
	// rpc ReadExchange(ReadReq) returns (ReadRes) {}
	ListExchange(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error)
}

type exchangesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangesServiceClient(cc grpc.ClientConnInterface) ExchangesServiceClient {
	return &exchangesServiceClient{cc}
}

func (c *exchangesServiceClient) Upvote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, "/proto.ExchangesService/Upvote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangesServiceClient) ListExchange(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/proto.ExchangesService/ListExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangesServiceServer is the server API for ExchangesService service.
// All implementations must embed UnimplementedExchangesServiceServer
// for forward compatibility
type ExchangesServiceServer interface {
	Upvote(context.Context, *VoteRequest) (*VoteResponse, error)
	// rpc CreateExchange(CreateReq) returns (CreateRes) {}
	// rpc ReadExchange(ReadReq) returns (ReadRes) {}
	ListExchange(context.Context, *Empty) (*ListResponse, error)
	mustEmbedUnimplementedExchangesServiceServer()
}

// UnimplementedExchangesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExchangesServiceServer struct {
}

func (UnimplementedExchangesServiceServer) Upvote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upvote not implemented")
}
func (UnimplementedExchangesServiceServer) ListExchange(context.Context, *Empty) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExchange not implemented")
}
func (UnimplementedExchangesServiceServer) mustEmbedUnimplementedExchangesServiceServer() {}

// UnsafeExchangesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangesServiceServer will
// result in compilation errors.
type UnsafeExchangesServiceServer interface {
	mustEmbedUnimplementedExchangesServiceServer()
}

func RegisterExchangesServiceServer(s grpc.ServiceRegistrar, srv ExchangesServiceServer) {
	s.RegisterService(&ExchangesService_ServiceDesc, srv)
}

func _ExchangesService_Upvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangesServiceServer).Upvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ExchangesService/Upvote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangesServiceServer).Upvote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangesService_ListExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangesServiceServer).ListExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ExchangesService/ListExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangesServiceServer).ListExchange(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangesService_ServiceDesc is the grpc.ServiceDesc for ExchangesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ExchangesService",
	HandlerType: (*ExchangesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upvote",
			Handler:    _ExchangesService_Upvote_Handler,
		},
		{
			MethodName: "ListExchange",
			Handler:    _ExchangesService_ListExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchanges.proto",
}
